# Generated by Django 3.0.7 on 2020-06-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('head0', models.CharField(default='', max_length=90)),
                ('chead0', models.CharField(default='', max_length=300)),
                ('head1', models.CharField(default='', max_length=90)),
                ('chead1', models.CharField(default='', max_length=300)),
                ('head2', models.CharField(default='', max_length=90)),
                ('chead2', models.CharField(default='', max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='blog/media')),
            ],
        ),
    ]
