# Generated by Django 3.0.7 on 2020-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=30)),
                ('desc', models.CharField(default='', max_length=30)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
