# Generated by Django 3.0.7 on 2020-06-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
